version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: question-app-ktor:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      app.db.prod.type: postgres
      app.db.prod.url: jdbc:postgresql://postgres:5432/postgres
      app.db.prod.user: postgres
      app.db.prod.password: postgres
      app.db.prod.schema: kask_question_ktor

